### ISSUE TITLE
Doublet detection in scATAC

### ISSUE THREAD

**Issue by ccruizm** [Militeee/rcongas#28]
Good day!

I want to apply your tool to a set of scATAC data and read in your latest pre-print that CONGAS+ can be used on this moldaity of data. However, I have not been able to find a vignette/tutorial/documentation on how to. 

Could you please address me where I can find that information?

Also, does CONGAS+ give a final classification for each cell to be aneuploid or diploid?

I really appreciate any help you can provide.

**Comment by caravagn** [comment]
@ccruizm Hi thanks for your message, @lucreziaPatruno is managing all the documentation etc and will be putting all material online asap. It would be nice to know if you can run CONGAS+ to identify doublets.

**Comment by ccruizm** [comment]
Thank you very much @caravagn for the info. Looking forward to trying it!

**Comment by Militeee** [comment]
The new vignette is up and the tool is published, so I close this one.
