### ISSUE TITLE
problem of Rcongas installing

### ISSUE THREAD

**Issue by Hane710477** [Militeee/rcongas#32]
I encountered an issue when installing the package and received the following message:
```
E  checking DESCRIPTION meta-information ... 
   Authors@R field gives more than one person with maintainer role:
     Salvatore Milite <militesalvatore@gmail.com> [aut, cre]
     Lucrezia Patruno <l.patruno@ucl.ac.uk> [aut, cre]
   
   See section 'The DESCRIPTION file' in the 'Writing R Extensions'
   manual.
Error: Failed to install 'Rcongas' from GitHub:
  ! System command 'Rcmd.exe' failed
```
Is there any method to handle this problem? ATM I could only install the package by modifying DESCRIPTION file to be only 1 maintainer.

**Comment by Militeee** [comment]
Hi @Hane710477  thanks for spotting this, we probably made some confusion now that we updated the Readme following the publication. Should be fixed now.

@lucreziaPatruno I added you as maintainer.
