### ISSUE TITLE
Interface to "multomics" model described in paper

### ISSUE THREAD

**Issue by mmyers1** [Militeee/rcongas#36]
I have multimodal 10x data (both RNA-seq and ATAC-seq measured from the same cells) and would like to use the "multomics" model (Fig. 2C in the PLoS Comp Bio paper) in which each cell is assigned to the same cluster in both modalities. However, the vignette for fitting a CONGAS+ model returns different cluster sizes between the two modalities, and I can't find a parameter to e.g. init() or fit_congas() to specify the multiomics model or that clusters should be consistent between modalities. Is there an interface available to the multiomics model?

**Comment by Militeee** [comment]
Correct me if I am wrong @lucreziaPatruno but setting the parameter `same_mixing = TRUE` in the `fit_congas` function should be enough to force the model to use the same assignments

**Comment by lucreziaPatruno** [comment]
Hi @mmyers1,
in addition to setting `same_mixing = TRUE` in the `fit_congas` function, you will need to re-run the `auto_config_run` function setting the parameter `multiome = TRUE`.
Please update your installation of the `Rcongas` package, as I just submitted a fix for a minor bug related to the multiome model.
BW
Lucrezia

**Comment by mmyers1** [comment]
Thanks! Using those instructions I was able to cluster the cells in the demo data consistently between the two modalities.
