### ISSUE TITLE
Filter output clusters

### ISSUE THREAD

**Issue by caravagn** [Militeee/rcongas#6]
We should ensure that when [we filter clusters](https://github.com/Militeee/rcongas/blob/master/R/filter_clusters.R) we do not just remove labels, but we actually re-compute the model score, latent variables and clustering assignments

**Comment by Militeee** [comment]
We already do that, just set the option `remove=FALSE`.

**Comment by caravagn** [comment]
Can you pleas add Riccardo to this repo so we can tag him along?

**Comment by Militeee** [comment]
The repo is public we can tag him, just it does not appear as tab autocompletion the first time. @riccardobergamin

**Comment by caravagn** [comment]
I had to fix this function as it was giving errors to @riccardobergamin

See [71d58d4d38c125a39e4c5b1033085f8fa4f4db2b]
